# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spam_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 417)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(13, 19, 441, 191))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_check = QtWidgets.QPushButton(Form)
        self.pushButton_check.setGeometry(QtCore.QRect(470, 20, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_check.setFont(font)
        self.pushButton_check.setObjectName("pushButton_check")
        self.pushButton_clear = QtWidgets.QPushButton(Form)
        self.pushButton_clear.setGeometry(QtCore.QRect(470, 120, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label_prob = QtWidgets.QLabel(Form)
        self.label_prob.setGeometry(QtCore.QRect(20, 230, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_prob.setFont(font)
        self.label_prob.setObjectName("label_prob")
        self.label_cat = QtWidgets.QLabel(Form)
        self.label_cat.setGeometry(QtCore.QRect(20, 280, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_cat.setFont(font)
        self.label_cat.setObjectName("label_cat")
        self.pushButton_true = QtWidgets.QPushButton(Form)
        self.pushButton_true.setGeometry(QtCore.QRect(20, 340, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_true.setFont(font)
        self.pushButton_true.setObjectName("pushButton_true")
        self.pushButton_false = QtWidgets.QPushButton(Form)
        self.pushButton_false.setGeometry(QtCore.QRect(210, 340, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_false.setFont(font)
        self.pushButton_false.setObjectName("pushButton_false")
        self.pushButton_ok = QtWidgets.QPushButton(Form)
        self.pushButton_ok.setGeometry(QtCore.QRect(400, 340, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("Form", "Введите сообщение"))
        self.pushButton_check.setText(_translate("Form", "Проверить\n"
"на спам"))
        self.pushButton_clear.setText(_translate("Form", "Очистить"))
        self.label_prob.setText(_translate("Form", "Вероятность спама 00.00%"))
        self.label_cat.setText(_translate("Form", "Введенное сообщение определено как СПАМ"))
        self.pushButton_true.setText(_translate("Form", "Верно"))
        self.pushButton_false.setText(_translate("Form", "Не верно"))
        self.pushButton_ok.setText(_translate("Form", "Ок"))
